In [21]:
import pandas as pd
import numpy as np
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [1]:
train_df = pd.read_csv("C:/Users/sravyay/Downloads/sample1.csv")

In [22]:
features = pd.get_dummies(train_df)
labels = np.array(features['Label'])
features= features.drop('Label', axis = 1)
feature_list = list(features.columns)
features = np.array(features)

In [23]:
from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [24]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

('Training Features Shape:', (9L, 7L))
('Training Labels Shape:', (9L,))
('Testing Features Shape:', (4L, 7L))
('Testing Labels Shape:', (4L,))


In [25]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
rf.fit(train_features, train_labels)
predictions = rf.predict(test_features)
errors = abs(predictions - test_labels)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')
mape = 100 * (errors / test_labels)
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

('Mean Absolute Error:', 0.0, 'degrees.')
('Accuracy:', 100.0, '%.')


In [2]:
train_data = train_df.values
labels = []
for i in train_data:
    labels.append(i[1])

In [3]:
print(labels)

['UA1', 'UA2', 'HA1', 'HA1', 'HA1', 'HA1', 'HA1', 'HA2', 'HA2', 'HA2', 'HA2', 'HA2', 'CA1']


In [6]:
values = array(labels)
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

#inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
#print(inverted)

['UA1' 'UA2' 'HA1' 'HA1' 'HA1' 'HA1' 'HA1' 'HA2' 'HA2' 'HA2' 'HA2' 'HA2'
 'CA1']
[3 4 1 1 1 1 1 2 2 2 2 2 0]
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.]]
['UA1']


In [8]:
for i in onehot_encoded:
    print i

[ 0.  0.  0.  1.  0.]
[ 0.  0.  0.  0.  1.]
[ 0.  1.  0.  0.  0.]
[ 0.  1.  0.  0.  0.]
[ 0.  1.  0.  0.  0.]
[ 0.  1.  0.  0.  0.]
[ 0.  1.  0.  0.  0.]
[ 0.  0.  1.  0.  0.]
[ 0.  0.  1.  0.  0.]
[ 0.  0.  1.  0.  0.]
[ 0.  0.  1.  0.  0.]
[ 0.  0.  1.  0.  0.]
[ 1.  0.  0.  0.  0.]


In [15]:
train = []
k = 0
X = []
Y = []
for i in train_data:
    if(i[2] == 'POD'):
        i[2] = 0
    else:
        i[2] = 1
    myarr=[i[0],onehot_encoded[k],i[2]]
    X.append(myarr)
    Y.append(i[3])
print(X)
print(Y)

[[1200L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [1210L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [2400L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [2410L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [2420L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [2430L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [5000L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [2400L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [2410L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [2420L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [2430L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [5000L, array([ 0.,  0.,  0.,  1.,  0.]), 1], [1800L, array([ 0.,  0.,  0.,  1.,  0.]), 1]]
[1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L]
